pipeline:
  name: new-pipeline
  identifier: newpipeline
  projectIdentifier: delivery
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: build1
        identifier: build1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "Hello Lavakush"
                  description: sample test
